name: Main Branch CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build succeeded"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Simulate deployment
        run: echo "Deploying..."

      - name: Force deployment failure
        run: |
          echo "Deployment failed intentionally."
          exit 1
